import { ArrowLeft, ArrowUpRight, Box, CheckCircle2, Clock3, MapPin, PackageCheck, Route, Search } from "lucide-react";

type Locale = "pt" | "en";

export function ShipTrackDemo({locale}:{locale:Locale}) {
  const pt = locale === "pt";
  return <main className="shiptrack-page" lang={pt?"pt-BR":"en"}>
    <nav className="shiptrack-nav shell"><a href={pt?"/":"/en"}><ArrowLeft size={17}/>{pt?"Voltar ao portfólio":"Back to portfolio"}</a><span>SHIPTRACK / API</span><a href="https://github.com/Morgana-Fstack/shiptrack-api" target="_blank" rel="noreferrer">GitHub<ArrowUpRight size={15}/></a></nav>
    <section className="shiptrack-hero shell"><div><p className="section-label">{pt?"Demonstração visual":"Visual demonstration"}</p><h1>{pt?"Entregas visíveis do início ao destino.":"Deliveries visible from dispatch to destination."}</h1><p>{pt?"Uma visão de produto para a API REST ShipTrack, criada para organizar rastreamento, persistência de dados e evolução de status em uma estrutura testável.":"A product view of the ShipTrack REST API, designed to organize tracking, data persistence and status updates in a testable structure."}</p></div><div className="tracking-card"><div className="tracking-search"><Search size={17}/><span>BR2026SP0419</span><button>{pt?"Rastrear":"Track"}</button></div><div className="package-head"><div><small>{pt?"Status atual":"Current status"}</small><strong>{pt?"Em trânsito":"In transit"}</strong></div><Route size={30}/></div><div className="tracking-line"><i className="done"/><i className="done"/><i className="active"/><i/></div><div className="tracking-labels"><span>{pt?"Coletado":"Collected"}</span><span>{pt?"Triagem":"Sorting"}</span><span>{pt?"Em trânsito":"In transit"}</span><span>{pt?"Entregue":"Delivered"}</span></div></div></section>
    <section className="shiptrack-content shell"><div className="shiptrack-stats"><article><Box/><span>REST</span><p>{pt?"Operações organizadas por recursos":"Resource-based operations"}</p></article><article><Clock3/><span>STATUS</span><p>{pt?"Histórico de movimentações":"Movement history"}</p></article><article><PackageCheck/><span>{pt?"TESTES":"TESTS"}</span><p>{pt?"Comportamentos verificáveis":"Verifiable behavior"}</p></article></div><div className="endpoint-panel"><div className="endpoint-copy"><p className="section-label">{pt?"Como funciona":"How it works"}</p><h2>{pt?"Do pedido à consulta em uma estrutura clara.":"From creation to tracking in a clear structure."}</h2><p>{pt?"A interface abaixo traduz visualmente o que o backend organiza: cadastro da entrega, atualização do percurso, consulta do status e registro persistente.":"The interface below visually translates what the backend organizes: shipment creation, route updates, status lookup and persistent records."}</p></div><div className="endpoint-list"><div><b>POST</b><code>/shipments</code><span>{pt?"Criar entrega":"Create shipment"}</span></div><div><b>PATCH</b><code>/shipments/:id/status</code><span>{pt?"Atualizar status":"Update status"}</span></div><div><b>GET</b><code>/shipments/:id</code><span>{pt?"Consultar rastreio":"Get tracking"}</span></div></div></div><div className="event-board"><div className="event-route"><MapPin/><div><small>CURITIBA / PR</small><strong>{pt?"Centro de distribuição":"Distribution center"}</strong><span>11 SEP · 09:42</span></div></div><ArrowUpRight className="event-arrow"/><div className="event-route"><CheckCircle2/><div><small>SÃO PAULO / SP</small><strong>{pt?"Próxima etapa":"Next checkpoint"}</strong><span>12 SEP · 16:20</span></div></div></div></section>
  </main>;
}
